{
	"version": 1766548624,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player2-sheet0.png",
		"images/objrr-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/gameหลอกตานะจ่ะ-sheet0.png",
		"images/sprite-sheet0.png",
		"images/golditem-sheet0.png",
		"images/www-sheet0.png",
		"images/obj_turret-sheet0.png",
		"images/odj_bullet-sheet0.png",
		"images/odj_bg1-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/btn_mute-sheet0.png",
		"images/btn_mute-sheet1.png",
		"images/obj_green-sheet0.png",
		"images/obj_red-sheet0.png",
		"media/ogg  geme_retro_jump_2-206573.ogg",
		"media/ogg  coin-upaif-14631.ogg",
		"media/annn-107540.ogg",
		"media/rifle-gun-shooting-391562.ogg",
		"media/cash-register-purchase-87313.ogg",
		"media/stab-f-01-brvhrtz-224599.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}